### ISSUE TITLE
Every JSON feed has an error on line 743

### ISSUE THREAD

**Issue by NetOpWibby** [vigetlabs/json-feed-validator#1]
This is with the official example, Daring Fireball's feed, and my own.

- https://jsonfeed.org/feed.json
- https://daringfireball.net/feeds/json
- https://thewebb.blog/feed/json

I found [this,](https://meetingguide.org/validate) but it's just for validating regular JSON.

**Comment by dce** [comment]
@NetOperatorWibby I'm unable to replicate. The official example doesn't have anywhere close to 743 lines, so that error is very surprising. Are you able to reproduce on https://json-feed-validator.herokuapp.com/ ?

**Comment by NetOpWibby** [comment]
@dce Yep!

<img width="508" alt="ss 2017-12-13 at 12 54 09 pm" src="https://user-images.githubusercontent.com/1288356/33953975-e7a147b6-e004-11e7-8689-1463d969c207.png">

I'm on macOS High Sierra using the new Firefox, if that helps.

**Comment by dce** [comment]
Oh, ok. This validator is expecting the (JSON) content of the feed, not the URL. Would probably make sense to make that a little bit clearer.

**Comment by NetOpWibby** [comment]
Ooh okay. Haha, welp. I'll close this issue then.

**Comment by NetOpWibby** [comment]
My feed validates!
