### ISSUE TITLE
JSON Feed v1.1 upgrade

### ISSUE THREAD

**Issue by lukasschwab** [vigetlabs/json-feed-validator#2]
Super useful tool, thanks for building and hosting it!

There's a new JSON Feed version, 1.1: https://jsonfeed.org/version/1.1

And there seems to be a schema published, though I don't know how this app handles `$ref` links to the previous schema: https://json.schemastore.org/feed.json

I'd really appreciate it if you get a chance to upgrade.

**Comment by dce** [comment]
Hey Lukas, just pushed an update and now it's validating the daringfireball.net feed (wasn't previously). Thanks for bringing this to our attention and have a good rest of your weekend.
